[package]
name = "mf-uci"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
embedded-net = ["mf-nnue/embedded-net"]

[[bin]]
name = "manifold"
path = "src/main.rs"

[dependencies]
mf-core = { path = "../mf-core" }
mf-datagen = { path = "../mf-datagen" }
mf-nnue = { path = "../mf-nnue" }
mf-search = { path = "../mf-search" }
